---
kind: pipeline
type: kubernetes
name: prod-build-push

steps:
  - name: build-push
    image: gcr.io/kaniko-project/executor:debug
    environment:
      USERNAME:
        from_secret: registry_username
      PASSWORD:
        from_secret: registry_password
      REGISTRY:
        from_secret: registry_address
    commands:
      - COMMIT=${DRONE_COMMIT_SHA:0:8}
      - RAW_BRANCH=${DRONE_BRANCH}
      - BRANCH=$(echo $RAW_BRANCH | sed 's/[^a-zA-Z0-9]/-/g')
      - TAG=$BRANCH-$COMMIT
      - API_IMAGE_NAME=$REGISTRY/nvideo-api:$TAG
      - WEB_IMAGE_NAME=$REGISTRY/nvideo-web:$TAG

      - AUTH=$(echo -n $USERNAME:$PASSWORD | base64 -w 0)
      - |
        JSON="{ \"auths\": { \"$REGISTRY\": { \"auth\": \"$AUTH\" } } }"
      - echo $JSON > "/kaniko/.docker/config.json"

      - |
        echo Building and pushing API service: $API_IMAGE_NAME
      - /kaniko/executor 
        --destination="$API_IMAGE_NAME" 
        --context="api_service" 
        --dockerfile="api_service/Dockerfile"

      - |
        echo Building and pushing Web service: "$WEB_IMAGE_NAME"
      - /kaniko/executor 
        --destination="$WEB_IMAGE_NAME" 
        --context="web_service" 
        --dockerfile="web_service/Dockerfile"

  - name: clone-infra
    image: alpine/git
    commands:
      - git clone https://github.com/Deeplerg/nvideo-infra

  - name: update-infra
    image: registry.k8s.io/kustomize/kustomize:v5.0.0
    environment:
      REGISTRY:
        from_secret: registry_address
    commands:
      - COMMIT=${DRONE_COMMIT_SHA:0:8}
      - BRANCH=main
      - TAG=$BRANCH-$COMMIT
      - API_IMAGE_NAME="$REGISTRY/nvideo-api:$TAG"
      - WEB_IMAGE_NAME="$REGISTRY/nvideo-web:$TAG"

      - cd nvideo-infra/kustomization/prod

      - |
        echo Updating Kustomize image for API: "$API_IMAGE_NAME"
      - kustomize edit set image nvideo-api-image-name-placeholder="$API_IMAGE_NAME"
      - |
        echo Updating Kustomize image for Web: "$WEB_IMAGE_NAME"
      - kustomize edit set image nvideo-web-image-name-placeholder="$WEB_IMAGE_NAME"

  - name: push-infra-changes
    image: alpine/git
    commands:
      - cd nvideo-infra
      - git checkout main
      - git config user.email "drone@deeplerg.dev"
      - git config user.name "Drone"
      - git add .
      - git commit -am "Update image tags" --author="Drone <drone@deeplerg.dev>" --allow-empty
      - git push

trigger:
  branch:
    - main
  event:
    - push


---
kind: pipeline
type: kubernetes
name: prod-build-only

steps:
  - name: build-no-push
    image: gcr.io/kaniko-project/executor:debug
    commands:
      - echo "Building API service"
      - /kaniko/executor 
        --no-push 
        --context="api_service" 
        --dockerfile="api_service/Dockerfile"

      - echo "Building Web service"
      - /kaniko/executor 
        --no-push 
        --context="web_service" 
        --dockerfile="web_service/Dockerfile"

trigger:
  branch:
    - main
  event:
    - pull_request
    #- push